version: 1

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF
formats:
- pdf

# Explicitly set the version of Python and its requirements
python:
  setup_py_install: true
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
        
# Build customization
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  jobs:
    post_checkout:
      - cat README.md > docs/index.md
      - cat docs/index_tree.md >> docs/index.md
      
